### ISSUE TITLE
Output encoded UTF-16 while Response header is UTF-8

### ISSUE THREAD

**Issue by labackp** [commerble/ODatalizer#2]
I have got UTF-16 strings in the ef core models (nvarchar in SQL Server is UTF-16 encoded by default. 
Entity Sets are retrieved in UTF-16 even when requested explicitely by an "Accept-Charset=utf-8" Request Header.
JSON Outputs should be UTF-8 by default, what can I do? Do you think this is an aspnetcore.odata issue?
Regards, Peter

**Comment by iwate** [comment]
Hi @labackp 

Our environment (ja-JP strings in nvarchar column) response utf8  body and the nvarchar string value was escaped.
```
{
  "@odata.context":"https://localhost:44335/ec/$metadata#Products(Name)/$entity",
  "Name":"\u30b5\u30f3\u30d7\u30eb\u5546\u54c1201"
}
```
I think it is correct behavior...

Would you tell us expects and actuals with a sample?

p.s.
ODatalizer is very thin wrapper for microsoft.aspnetcore.odata, you known.
May be, I think that it is thire issue or just settings of  microsoft.aspnetcore.odata, efcore, aspnetcore.

**Comment by labackp** [comment]
Hi @iwate 
Thank you for your answer! I would have expected the json strings to be escaped with UTF-8 encoding if I request a utf8 encoding, but this is not the case. I just want to make sure that the output is readable by a wide range of browsers an their javascript engines. 
SQL Server 2019 has got a new collation group with utf8 encoding, but nvarchar will always be encoded utf16.  
So thank you for your help, I will try this my first wabapi odata implemenation "as is" and will let you know if there are issues on the consumer side.
Best regards, Peter

**Comment by labackp** [comment]
Thank you for clarification!

**Comment by iwate** [comment]
Note:

Microsoft.OData.Core has own JSON Serializer, don't use System.Text.Json or Newtonsoft.Json
https://github.com/OData/odata.net/tree/master/src/Microsoft.OData.Core/Json

Microsoft.OData.Core.Json has two escape modes.
https://github.com/OData/odata.net/blob/9788e845f5664642f990c02b6a5fec7c7df7febd/src/Microsoft.OData.Core/Json/ODataStringEscapeOption.cs#L12-L24

And default use `EscapeNonAscii`
https://github.com/OData/odata.net/blob/9788e845f5664642f990c02b6a5fec7c7df7febd/src/Microsoft.OData.Core/ContainerBuilderExtensions.cs#L134

https://github.com/OData/odata.net/blob/9788e845f5664642f990c02b6a5fec7c7df7febd/src/Microsoft.OData.Core/Json/DefaultJsonWriterFactory.cs#L32-L35

I try override the factory in ODatalizer.EFCore.EndpointRouteBuilderExtensions and get unespaced payload.
```
public static void MapODatalizer(this IEndpointRouteBuilder builder, params ODatalizerEndpoint[] endpoints)
        {
            builder.Select().Expand().Filter().OrderBy().MaxTop(100).Count().SkipToken();
            foreach (var ep in endpoints)
            {
                builder.MapODataRoute(ep.RouteName, ep.RoutePrefix, b => {
                    // ---- add here ------
                    b.AddService<IJsonWriterFactory>(ServiceLifetime.Singleton, sp => new DefaultJsonWriterFactory(ODataStringEscapeOption.EscapeOnlyControls));
                    // --------------------
                    b.AddService(ServiceLifetime.Singleton, sp => ep.EdmModel);
                    b.AddService<ODataBatchHandler>(ServiceLifetime.Singleton, sp => new ODatalizerBatchHandler());
                    b.AddService<ODataDeserializerProvider>(ServiceLifetime.Singleton, sp => new DefaultODataDeserializerProvider(sp));
                    b.AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp => {
                        var conventions = ODataRoutingConventions.CreateDefaultWithAttributeRouting(ep.RouteName, builder.ServiceProvider);
                        if (string.IsNullOrEmpty(ep.ODatalizerController) == false)
                        {
                            conventions.Add(new ODatalizerDynamicConvention(ep.ODatalizerController.Replace("Controller", string.Empty)));
                        }
                        return conventions;
                    });
                });
            }
        }
    }
```
