### ISSUE TITLE
MaxExpansionDepth

### ISSUE THREAD

**Issue by VictorQualitas** [commerble/ODatalizer#3]
How to set MaxExpansionDepth for all dbcontext in ODatalizer?

**Comment by iwate** [comment]
Hi @VictorQualitas 

We have released new version 5.0.6.0.
You can set MaxExpansionDepth settings to `ODatalizerEndpoint.` in Startup

```
var ep = new ODatalizerEndpoint(
                            db: sample,                             
                            routeName: "Sample", 
                            routePrefix: "sample") {
                                MaxExpansionDepth  = 5
                            };
```

if you use dynamic controller feature, you need override `Get` method and set `EnableQuery` settings :)
https://github.com/commerble/ODatalizer/blob/5e140c0c1a60deeefb14728be2a261fe3437d051/src/Sample.EFCore/Controllers/SampleController.cs#L23-L31
